#!/usr/bin/env bash
# Launch the harbor + E2B PGC SWE recipe.
# Run from the NeMo RL repo root (`/scratch/yuzhou/projects/RL` here).
#
# Loads E2B_API_KEY + WANDB_API_KEY from research/pgc_swe/.env (gitignored)
# so the user does not have to remember to `export` them manually each session.
#
# Pass extra Hydra overrides on the command line, e.g.:
#   bash research/pgc_swe/run_harbor_e2b.sh \
#       data.train.data_path=$DATA_DIR/scientific_train.jsonl \
#       data.validation.data_path=$DATA_DIR/scientific_val.jsonl \
#       grpo.max_num_steps=20

set -euo pipefail
set -x

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Use all 8 GPUs by default (matches yaml's cluster.gpus_per_node=8).
# Override with e.g. CUDA_VISIBLE_DEVICES=0,1,6,7 when sharing the box;
# remember to also drop cluster.gpus_per_node accordingly.
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}"

# Load secrets
if [ -f "${SCRIPT_DIR}/.env" ]; then
    set -a
    # shellcheck disable=SC1091
    source "${SCRIPT_DIR}/.env"
    set +a
fi
: "${E2B_API_KEY:?E2B_API_KEY missing — put it in research/pgc_swe/.env}"

cd "${REPO_ROOT}"

# Default training/validation jsonl files (generated by
# `research/pgc_swe/scripts/prep_harbor_jsonl.py`). Override on the command
# line if you want a different subset / split.
DATA_DIR="${REPO_ROOT}/research/pgc_swe/data"

# `uv` (used by NeMo Gym to materialise its own venvs) shells out to git, and
# the system `LD_LIBRARY_PATH` (CUDA libs) makes /usr/bin/git SIGSEGV on this
# machine. Strip it for the trainer; CUDA libs come from the .venv wheels.
unset LD_LIBRARY_PATH

# Use system CUDA 13.2 — matches torch+cu130 wheels in our pyproject (we
# ported NeMo RL upstream PR #2332's cu13 migration). System default
# /usr/local/cuda symlinks to /usr/local/cuda-13.2 on both H200 (sm_90) and
# B300 (sm_103). nvcc/ptxas in here is what `deep-ep`, `transformer-engine`,
# `mamba-ssm`, `causal-conv1d` will pick up when their setup.py invokes
# torch.utils.cpp_extension.
export CUDA_HOME=/usr/local/cuda-13.2
export PATH="${CUDA_HOME}/bin:${PATH}"

# Cover Hopper (sm_90, H200) + Blackwell base (sm_100, B200). B300 reports
# sm_103 in nvidia-smi but PTX targets are forward-compatible from sm_100,
# so a kernel built for 10.0 runs on 10.3. Listing both keeps the same
# build artifacts usable across both classes of GPU on the same box.
# Megatron's worker_extension refuses to start without this set inside Ray
# subprocesses where CUDA may not be initialized yet.
export TORCH_CUDA_ARCH_LIST="9.0 10.0"

# CUDA 13 moved a chunk of the standard library headers into
# include/cccl. deep_gemm and similar build-from-source kernels include
# <cuda/std/...> directly and fail at compile if cccl/ isn't on the include
# path. Mirror PR #2332's Dockerfile env var.
#
# Note: TE rev 71bbefbf has a known build bug where
# `transformer_engine/common/util/logging.h:15` unconditionally
# `#include "nccl.h"` even though CMakeLists.txt only adds the nccl include
# path when `NVTE_WITH_CUBLASMP=ON`. NVIDIA's docker base image
# (nvcr.io/cuda-dl-base) hides this because nccl ships in
# /usr/local/cuda/include there. On bare metal it doesn't — install
# nccl headers system-wide once with:
#   sudo apt install libnccl-dev    # gives /usr/include/nccl.h, on gcc default search path
# After that no extra env var is needed; gcc/nvcc find nccl.h naturally.
export CPLUS_INCLUDE_PATH=/usr/local/cuda/include/cccl${CPLUS_INCLUDE_PATH:+:${CPLUS_INCLUDE_PATH}}

# Note: `PYTORCH_ALLOC_CONF=expandable_segments:True` would help fragmentation
# during the Megatron→vLLM refit all_gather, but it crashed vLLM's NCCL init
# (`Failed to CUDA calloc async 16 bytes` at `determine_available_memory`)
# on the H200 + NCCL 2.27.5 + vllm 0.17.1 cu129 stack. Re-evaluate with the
# cu130 stack — NCCL is now 2.28.9 — but for now don't set it; instead lower
# `policy.generation.vllm_cfg.gpu_memory_utilization` to leave headroom.

# `deep-ep` (RDMA-aware MoE all-to-all from DeepSeek) is in nemo-rl[vllm].
# Building it from source needs `infiniband/mlx5dv.h` from rdma-core. The
# system has no /usr/include/infiniband — install once via:
#   conda install -n base -c conda-forge rdma-core -y
# and point the build at the conda headers + libs:
CONDA_PREFIX_RDMA=/scratch/yuzhou/miniconda3
export CPATH="${CONDA_PREFIX_RDMA}/include${CPATH:+:${CPATH}}"
export LIBRARY_PATH="${CONDA_PREFIX_RDMA}/lib${LIBRARY_PATH:+:${LIBRARY_PATH}}"
# Note: we keep the runtime LD_LIBRARY_PATH unset (see the unset above) — the
# deep-ep .so links against rdma-core at build time but the runtime libibverbs
# is found via the system /lib/x86_64-linux-gnu/libibverbs.so.1.

# transformer-engine + deep-ep + mamba-ssm + causal-conv1d need to be built
# from CUDA sources into the per-worker mcore venv. NeMo RL's `_env_builder`
# Ray actor runs `uv sync --extra mcore` once per worker venv, but if any
# build fails (cmake missing, etc) the resulting venv silently lacks TE and
# the megatron worker then crashes with `ModuleNotFoundError: transformer_engine`.
# Pre-build into the venv ourselves (idempotent — uv reuses cached wheels):
MCORE_VENV="${REPO_ROOT}/venvs/nemo_rl.models.policy.workers.megatron_policy_worker.MegatronPolicyWorker"
if [ ! -d "${MCORE_VENV}/lib/python3.13/site-packages/transformer_engine" ]; then
    echo "[run_harbor_e2b] pre-building transformer_engine + deps into mcore venv..."
    UV_PROJECT_ENVIRONMENT="${MCORE_VENV}" \
        uv sync --extra mcore --directory "${REPO_ROOT}"
fi

# Pre-build the harbor_agent venv ourselves (otherwise NeMo Gym builds it on
# demand inside its __init__, and the requirements + override files we use
# wouldn't be wired in).
#
# We bypass the upstream `responses_api_agents/harbor_agent/requirements.txt`
# entirely and use our own pin file under research/pgc_swe/configs/. That
# avoids dirtying the Gym submodule with our project-specific harbor pin
# and openai override.
HARBOR_AGENT_DIR="${REPO_ROOT}/3rdparty/Gym-workspace/Gym/responses_api_agents/harbor_agent"
HARBOR_REQS="${SCRIPT_DIR}/configs/harbor_agent_requirements.txt"
HARBOR_OVERRIDES="${SCRIPT_DIR}/configs/harbor_agent_overrides.txt"
if [ ! -d "${HARBOR_AGENT_DIR}/.venv" ]; then
    echo "[run_harbor_e2b] pre-building harbor_agent venv from ${HARBOR_REQS}"
    # Pin ray to the version in NeMo RL's main venv. NeMo Gym's harbor_agent
    # actor connects to the same Ray cluster the trainer started, and Ray
    # mismatches (e.g. 2.54 vs 2.55) abort the actor at startup with
    # `RuntimeError: Version mismatch`. The override file forces openai
    # past nemo-gym's `openai<=2.7.2` cap so latest harbor + its newer
    # litellm dep resolve cleanly.
    NEMORL_RAY_VERSION=$("${REPO_ROOT}/.venv/bin/python" -c \
        "import ray; print(ray.__version__)")
    (cd "${HARBOR_AGENT_DIR}" && uv venv --python 3.13 .venv && \
        VIRTUAL_ENV=.venv uv pip install \
            -r "${HARBOR_REQS}" \
            --override "${HARBOR_OVERRIDES}" \
            "ray==${NEMORL_RAY_VERSION}")
fi

"${REPO_ROOT}/.venv/bin/python" examples/nemo_gym/run_grpo_nemo_gym.py \
    --config research/pgc_swe/configs/grpo-qwen3.5-9b-1n8g-harbor-e2b.yaml \
    data.train.data_path="${DATA_DIR}/scientific_train.jsonl" \
    data.validation.data_path="${DATA_DIR}/scientific_val.jsonl" \
    "$@"
