defaults: ./grpo-moonlight-16b-automodel-1n8g-ep8.yaml
policy:
  sequence_packing:
    enabled: true
  dynamic_batching:
    enabled: false
  dtensor_cfg:
    context_parallel_size: 2
checkpointing:
  checkpoint_dir: results/grpo-moonlight-16b-automodel-1n8g-cp2ep4-seqpack
