defaults: ./sft-gpt-oss-20b-1n8g-pp2ep4-automodel.yaml
sft:
  val_at_start: false
policy:
  sequence_packing:
    enabled: true
  dtensor_cfg:
    context_parallel_size: 2
checkpointing:
  checkpoint_dir: results/sft-gpt-oss-20b-1n8g-pp2cp2ep2-seqpack-automodel
